### ISSUE TITLE
evo version

### ISSUE THREAD

**Issue by jmlongriver12** [AmeyaHarmalkar/therML#1]
Hi, I got an error when running "python supervised.py" under "ab-ptlm" folder, the error message is "ModuleNotFoundError: No module named 'evo.tokenization'", I wonder which evo should be installed, thanks

**Comment by AmeyaHarmalkar** [comment]
Hi, 
If you could cp the `evo` directory from the ptlm directory to the `ab-ptlm` directory, it would work fine. Thanks for pointing it out. I will edit the README to reflect this.
